name: HyperTraPS
channels:
  - etetoolkit
  - conda-forge
  - defaults
dependencies:
  - python=2.7.16
  - numpy=1.16.4
  - scipy=1.2.1
  - matplotlib=2.2.3
  - pandas=0.24.2
  - networkx=2.1
  - statsmodels=0.9.0
  - ete3=3.1.1
  - seaborn=0.9.0
  - jupyterlab
